### PR TITLE
Setup the conda environment with YAML files

### PR DESCRIPTION
**Pull request by LexSong**
Using environment YAML files helps us maintain the dependencies in the long run.

The conda environment files are based on @henk717's scripts and should produce the exact same environment.

### CODE REVIEW

**Comment by henk717** [comment]
Jumped ahead of this commit a bit since i was working on a new install experience based on Mamba.
To get the best results i had to change a few things around especially since the huggingface one failed to install, so rather than a KoboldAI.yml with shared dependencies i made 2 environments with all the dependencies in it.

ROCm is quite a mess, so i decided not to use an environment file for it at the moment since doing it properly from scratch is seemingly undocumented. Its easier to just have that one be done exclusively by its docker file.

This specific merge request installs the files in a different location than the previous version did, so i'd rather avoid that to avoid more confusion in supporting the users. The new mamba based script still uses environment files but will install this in the same miniconda3 folder as the previous version to preserve compatibiltiy.

Let me know what the best approach is for you, i can try and commit my installers / docker files to your branch so you can do a new pull request from there, or i can submit my own pull request to this main branch once the docker side of things has been properly tested (Test files are currently distributed in discord).

**Comment by LexSong** [comment]
My personal use case is using only the YAMLs to create environments only.
I don't really need the install script or one key installation.

As long as there's an environment file that I could easily use on my own. I would be happy.
You could modify the installation as you see fit.

**Comment by henk717** [comment]
Included the environment files that work across my docker and mamba installers in the https://github.com/KoboldAI/KoboldAI-Client/pull/59 pull

**Comment by LexSong** [comment]
Closed after #59

**Pull request closed without merging**
