### PR TITLE
Makes KoboldAI webserver configurable settings for connecting to it from another device

### PR DESCRIPTION
**Pull request by tralezab**
## Forewarning

I am pretty terrible at python, sorry in advance for doing some bad practices!

## About The Pull Request

KoboldAI now has a "main menu" where you can choose to go ahead to the model selection and server starting, but also over to server settings. Here you can enable and configure a server to host the webserver on instead of 0.0.0.0:5000

This is so you can, say, let your computer run KoboldAI while you use your phone, or whatever other device you want to.

This also means that you can technically do multiplayer with this, but it's more of a consequence of freedom rather than anything else. I haven't hooked up updates to all other clients when one sends an input, so it's a pretty bad multiplayer at the moment. Something about unencrypted data, too. Either way, technically those problems could be solved in the future and we could have true multiplayer which is neat, so I don't think it's an issue right now.

todo:
- [ ] clean up code
- [ ] fix colors not formatting correctly

image

### CODE REVIEW

**Comment by UWUplus** [comment]
I personally see an issue with this not being secured in any way, as anyone can read your stories by opening it up like this. 
Maybe this could be looked at along with the multiplayer option, [mentioned by KoboldAI on Reddit. ](https://www.reddit.com/r/KoboldAI/comments/nms8jh/koboldai_anywhere_cloudflare_access/gzqh58f/)

**Comment by tralezab** [comment]
A couple things to ease your thoughts on this:
1. it starts disabled, and the defaults for connection is 0.0.0.0 which is a non-working address.
2. when enabled but not set up correctly, it errors. so there really isn't any way to not know what you're doing and accidentally expose the story to others.

With that said, I do like the idea of multiplayer as I mentioned in OP and if multiplayer is going to be a real option and not a /terrible/ idea people can technically do security is a must + actual multiplayer input updating

**Comment by UWUplus** [comment]
If I recall correctly 0.0.0.0 binds flask to any Interface, with it being disabled by default, that's okay though. In my opinion there should be a warning though, that If you don't have any firewall in front of your client anyone can access. 

But that's just my opinion as someone working with *too many* stupid users. lol

**Comment by KoboldAI** [comment]
It'll have a warning. I'm trying to get the start menu revamp out this week, which will have the webserver option in it. I'm on a work trip for my regular job though, so I'll have less time to work on Kobold than usual until I get back.

**Comment by tralezab** [comment]
Honestly, if you're making a webserver option and a menu revamp, I think I should just let you do that.

**Pull request closed without merging**
