### PR TITLE
Test version that works with Google Colab TPU

### PR DESCRIPTION
**Pull request by arcticlinux**
- add testing configuration
- break out mesh-transformer-jax dependencies and exclude jax and bleach
- "update" jax to 0.3.5, the default installed version on Colab
- update chex to 0.1.6 for jax 0.3.5 compatibility
- change tpu_mtj_backend.py TPU initialization, left in debugging statements

How this works is the Colab environment comes with jax and jaxlib 0.3.5 pre-installed with libtpu installed that allows it to talk to the TPU.  Similar to installing per the [instructions](https://github.com/google/jax#pip-installation-google-cloud-tpu):

`pip install jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`
I tried this version, but couldn't actually get a manually installed version working.

I don't believe they have a version 0.4.x that works in this way, I think it works in a different way.

This also does installation of the requirements from mesh-transformers-jax in a funny way to avoid having to modify that repository as well, it installs all of it's requirements (minus jax/jaxlib and bleach, I was trying to for bleach 6.0.0 which is also pre-installed in Colab, but the interface is different), and then installed that branch without requirements.

### CODE REVIEW

**Comment by Devetec** [comment]
I remember I saw a fix at some point which required the user to have Colab Pro or Pro+, is this still an issue with this?

**Comment by arcticlinux** [comment]
I was just working with the free version.

There is another pull request that looks like it fixes more of the
underlying issues, as I only really tested getting the model/tensors loaded
with the jax driver.

**Comment by henk717** [comment]
Someone got it working properly yesterday on United. Your version does changes I don't want upstream since it uses new url's for the scripts and it also doesn't fix the parts that need to be fixed. I tried a fix almost identical to this myself and while it loads it often spews gibberish once you generate.

So I am going to close this one in favor of a backport of the fix we have in United to keep the fixes identical.

**Comment by arcticlinux** [comment]
I agree, it was more of a beginning of a fix for discussion that at least got the jax driver working.

**Pull request closed without merging**
